version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    nodejs: "18"
  apt_packages:
    - libarchive-dev

  jobs:
    pre_build:
      - jlpm --frozen-lockfile
      - jlpm build
      # re-install after the labextension is built
      - python -m pip install . --no-deps --ignore-installed --no-build-isolation
      # pre-build the lite site to isolate build errors
      - cd examples && jupyter lite build

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
        - docs

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
