version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
    nodejs: '18'
  apt_packages:
    - libarchive-dev

  jobs:
    pre_build:
      - jlpm --frozen-lockfile
      - jlpm build
      - jlpm dist
      # TODO: remove
      - |-
        python -m pip install --force-reinstall https://jupyterlite.rtfd.io/en/latest/_static/jupyterlite-0.1.0b18-py3-none-any.whl
      # pre-build the lite site to isolate build errors
      - jlpm docs:lite

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
        - docs

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
