version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    nodejs: "18"
  apt_packages:
    - libarchive

  jobs:
    pre_build:
      - jlpm --frozen-lockfile
      - jlpm build

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
        - docs

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
