version: 2
build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_install:
      - python -m pip install ".[dev]"
      - yarn
      - yarn run build
conda:
  environment: docs/environment.yml
sphinx:
   configuration: docs/conf.py
