[build-system]
requires = ["hatchling>=1.24"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "ipykernel/__init__.py"

[project]
name = "ipykernel"
authors = [
    {name = "JupyterLite Contributors"},
]
readme = "README.md"
requires-python = ">=3.11,<3.12"
dynamic = ["version", "description"]
classifiers = [
    "License :: OSI Approved :: BSD License",
]

[project.urls]
Source = "https://github.com/jupyterlite/pyodide-kernel"
