// this file is autogenerated from the wheels described in ../package.json
export * as allJSONUrl from '../pypi/all.json';
export * as ipykernelWheelUrl from '../pypi/ipykernel-6.9.2-py3-none-any.whl';
export * as pipliteWheelUrl from '../pypi/piplite-0.6.0a3-py3-none-any.whl';
export * as pipliteWheelUrl1 from '../pypi/piplite-0.6.0a4-py3-none-any.whl';
export * as pyodide_kernelWheelUrl from '../pypi/pyodide_kernel-0.6.0a3-py3-none-any.whl';
export * as pyodide_kernelWheelUrl1 from '../pypi/pyodide_kernel-0.6.0a4-py3-none-any.whl';
export * as widgetsnbextensionWheelUrl from '../pypi/widgetsnbextension-3.6.999-py3-none-any.whl';
export * as widgetsnbextensionWheelUrl1 from '../pypi/widgetsnbextension-4.0.999-py3-none-any.whl';
