// this file is autogenerated from the wheels described in ../package.json
export * as allJSONUrl from '../pypi/all.json';
export * as ipykernelWheelUrl from '../pypi/ipykernel-6.9.2-py3-none-any.whl';
export * as jediWheelUrl from '../pypi/jedi-0.18.2-py3-none-any.whl';
export * as jupyterlab_widgetsWheelUrl from '../pypi/jupyterlab_widgets-1.1.2-py3-none-any.whl';
export * as jupyterlab_widgetsWheelUrl1 from '../pypi/jupyterlab_widgets-3.0.5-py3-none-any.whl';
export * as pipliteWheelUrl from '../pypi/piplite-0.0.4-py3-none-any.whl';
export * as prompt_toolkitWheelUrl from '../pypi/prompt_toolkit-3.0.36-py3-none-any.whl';
export * as pyodide_kernelWheelUrl from '../pypi/pyodide_kernel-0.0.4-py3-none-any.whl';
export * as repodataJSONUrl from '../pypi/repodata.json';
export * as widgetsnbextensionWheelUrl from '../pypi/widgetsnbextension-3.6.0-py3-none-any.whl';
export * as widgetsnbextensionWheelUrl1 from '../pypi/widgetsnbextension-4.0.2-py3-none-any.whl';
