// this file is autogenerated from the wheels described in ../package.json
export * as allJSONUrl from '../pypi/all.json';
export * as ipykernelWheelUrl from '../pypi/ipykernel-6.29.4-py3-none-any.whl';
export * as pipliteWheelUrl from '../pypi/piplite-0.4.0a2-py3-none-any.whl';
export * as pyodide_kernelWheelUrl from '../pypi/pyodide_kernel-0.4.0a2-py3-none-any.whl';
export * as widgetsnbextensionWheelUrl from '../pypi/widgetsnbextension-3.6.6-py3-none-any.whl';
export * as widgetsnbextensionWheelUrl1 from '../pypi/widgetsnbextension-4.0.11-py3-none-any.whl';
