[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "widgetsnbextension/__init__.py"

[project]
name = "widgetsnbextension"
authors = [
    {name = "JupyterLite Contributors"},
]
readme = "README.md"
requires-python = ">=3.12,<3.13"
dynamic = ["version", "description"]
classifiers = [
    "License :: OSI Approved :: BSD License",
]

[project.urls]
Source = "https://github.com/jupyterlite/pyodide-kernel"
