name: Check Release
on:
  push:
    branches:
      - main
      - 0.1.x
  pull_request:
    branches:
      - '*'

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
        with:
          node_version: '20.x'
          python_version: '3.11'

      - name: Check Release
        uses: jupyter-server/jupyter_releaser/.github/actions/check-release@v2
        with:
          version_spec: next
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Distributions
        uses: actions/upload-artifact@v4
        with:
          name: jupyterlite-pyodide-kernel-releaser-dist-${{ github.run_number }}
          path: .jupyter_releaser_checkout/dist
